"""Add walletpay table

Revision ID: 84938f04bc17
Revises: 567414157553
Create Date: 2023-11-21 19:33:53.639484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84938f04bc17'
down_revision = '567414157553'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pay_transactions',
                    sa.Column('uuid', sa.BigInteger(), nullable=False),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.Column('description', sa.String(256), nullable=False),
                    sa.Column('status', sa.String(256), nullable=False),
                    sa.Column('submonth', sa.String(256), nullable=False),
                    sa.Column('subscription', sa.String(256), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('modified_at', sa.DateTime(), nullable=False),
                    sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id', ondelete='CASCADE')),
                    sa.PrimaryKeyConstraint('uuid'),
                    )
    op.execute('ALTER TABLE pay_transactions CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci')
    # ### end Alembic commands ###

def downgrade() -> None:
    op.drop_table('pay_transactions')
