"""empty message

Revision ID: ece13c4c6f65
Revises: d02dcfbf1517, b3378dc6de01
Create Date: 2023-02-23 14:55:19.953972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece13c4c6f65'
down_revision = ('d02dcfbf1517', 'b3378dc6de01')
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('node_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'node_id')
    )
    op.create_index(op.f('ix_node_user_id'), 'node_user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_user_id'), table_name='node_user')
    op.drop_table('node_user')
    # ### end Alembic commands ###
